include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    "**/*.d.dart"

linter:
  rules:
    avoid_web_libraries_in_flutter: false
    prefer_relative_imports: true
    prefer_single_quotes: true
    unnecessary_await_in_return: true
    prefer_final_locals: true
    prefer_final_fields: true
    avoid_unused_constructor_parameters: true
    always_declare_return_types: true
    require_trailing_commas: true