name: delivery_backoffice_dw10
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_modular: ^5.0.3
  loading_animation_widget: ^1.2.0+4
  mobx: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - .env
